# Generated by Django 4.0.6 on 2022-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
