# Generated by Django 4.0.6 on 2022-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(blank=True, default='media/img/default-avatar.jpg', null=True, upload_to='img/'),
        ),
    ]
